# Generated by Django 5.0.6 on 2024-10-06 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_myku_password_user_myku_student_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.CharField(max_length=10, unique=True)),
                ('name_th', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('religion', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name_th', models.CharField(max_length=255)),
                ('major_name_th', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('degree_name', models.CharField(max_length=255)),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='accounts.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='accounts.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='GroupCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_date', models.CharField(max_length=50)),
                ('subject_code', models.CharField(max_length=10)),
                ('subject_name', models.CharField(max_length=255)),
                ('teacher_name', models.CharField(max_length=255)),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_courses', to='accounts.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=10)),
                ('subject_code', models.CharField(max_length=10)),
                ('subject_name', models.CharField(max_length=255)),
                ('credit', models.FloatField()),
                ('grade', models.CharField(max_length=2)),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='accounts.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='GPAX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpax', models.FloatField()),
                ('total_credit', models.IntegerField()),
                ('student_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gpax', to='accounts.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announce_message_th', models.TextField()),
                ('teacher_name', models.CharField(max_length=255)),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='accounts.studentprofile')),
            ],
        ),
    ]
