# Generated by Django 5.0.6 on 2024-10-06 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_studentprofile_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='academic_year',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='grade',
            name='subject_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='groupcourse',
            name='subject_code',
            field=models.CharField(max_length=20),
        ),
    ]
