# Generated by Django 5.0.6 on 2024-10-24 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_onetimepassword_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='std_code',
            field=models.CharField(default=0, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
