# Generated by Django 5.0.6 on 2024-10-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_studentprofile_std_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupcourse',
            name='day_w',
            field=models.CharField(default='N/A', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupcourse',
            name='room_name_th',
            field=models.CharField(default='N/A', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupcourse',
            name='time_from',
            field=models.CharField(default='N/A', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupcourse',
            name='time_to',
            field=models.CharField(default='N/A', max_length=10),
            preserve_default=False,
        ),
    ]
