# Generated by Django 5.0.6 on 2024-10-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_groupcourse_day_w_groupcourse_room_name_th_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='subject_name',
            new_name='subject_name_th',
        ),
        migrations.AddField(
            model_name='grade',
            name='gpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='semester',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='subject_name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='total_credits',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
