# Generated by Django 5.0.6 on 2024-10-29 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_studentprofile_ku_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='myku_password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='myku_student_data',
        ),
        migrations.RemoveField(
            model_name='user',
            name='myku_username',
        ),
    ]
