# Generated by Django 5.0.6 on 2024-11-05 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_event_end_time_event_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingschedule',
            name='subject_code',
            field=models.CharField(default='N/A', max_length=20),
            preserve_default=False,
        ),
    ]
